### Recuperar todas las peliculas
##GET http://localhost:3000/movies

GET https://rest-api-deploy-phi.vercel.app/movies

### Recuperar una pelicula por id
GET http://localhost:3000/movies/c906673b-3948-4402-ac7f-73ac3a9e3105

### Recuperar una pelicula por un género
GET http://localhost:3000/movies?genre=action

### Crear una nueva pelicula con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Interstellar",
    "year": 2014,
    "director": "Christopher Nolan",
    "duration": 169,
    "poster": "https://m.media-amazon.com/images/I/91obuWzA3XL._AC_UF1000,1000_QL80_.jpg",
    "genre": [
        "Adventure",
        "Drama",
        "Sci-Fi"
    ]
}

### Actualizar una pelicula
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "title": "Hola",
    "year": 1998
}